import Head from 'next/head'
import Link from 'next/link'
import conectarDB from '../lib/dbConnect'
import Movie from '../models/Movie'


export default function Home({movies}) {    // revive el props destructurado
  console.log(movies)
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='container text-danger'>
        <h1>Movies</h1>

        <Link href="/new">
          <a className='btn btn-primary w-100 mb-2'>Agregar</a>
        </Link>

        {
          movies.map(({_id, title, plot}) => (
            <div className='card mb-2' key={_id}>
              <div className="car-body">
                <div className="h5 text-uppercase">{title}</div>
                <p className="fw-light">{plot}</p>
                <Link href={`${_id}`}>
                    <a className="btn btn-success btn-sm me-2">Más info ...</a>
                </Link>
              </div>
            </div>

          ))
        }
      </main>

    </div>
  )
}

export async function getServerSideProps() {
  try {
    await conectarDB()
    const res = await Movie.find({})   // devolverá la colección completa
    console.log("Respuesta de getServerSideProps() 🚀👀")

    // antes hacer un recorrido de todos los objetos, se debe convertir el objeto extraño _id a string
    const movies = res.map( doc => {
      const movie = doc.toObject()
      movie._id = `${movie._id}`  // convierte a string como toString()
      return movie
    })

    //console.log(res)
    return {props: {movies: movies}}

  } catch (error) {
    console.log("Errores de getServerSideProps()  😂😂😂")
    console.log(error)
  }
}
